### ISSUE TITLE
CI: Disable duplicate run on Push and PR

### ISSUE THREAD

**Issue by madig** [source-foundry/fdiff#15]
Annoyingly, both Travis and Appveyor must be configured to not run CI twice if you push to a PR branch on the main repo.

travis.yml and appveyor.yml:
```YAML
# The following prevents Travis from running CI on pull requests that come from a
# branch in the same repository. Without this, it will run the same CI for the
# pull request branch _and_ the pull request itself, which makes no sense.
branches:
  only:
    - master
    # We want to build wip/* branches since these are not usually used for PRs
    - /^wip\/.*$/
    # We want to build version tags as well.
    - /^v\d+\.\d+.*$/
```
